### ISSUE TITLE
[Feature Request] Showing size diff between version

### ISSUE THREAD

**Issue by NBprojekt** [carlesnunez/check-my-bundlephobia#8]
It would be nice to see the size difference when e.g.: updating packages.

Lets say you use [Dependabot][1] to update you dependencies. Dependabot will show you (when available) the new features, bug fixes or braking changes.  
 
What i'm interested in before I merge the update is:
- Do I need this Feature?
- Is it a security update?
- Does it make my dependencies bigger?
  Or even better smaller?

Therefore i would like to use the action with some additional information in the review e.g:  
Bump Moment from 2.24.0 to 2.25.3 (threshold: 67kB)

|      |                               name                               |    gzip   |   size   | pass |
|:----:|:----------------------------------------------------------------:|:---------:|:--------:|:----:|
| Old  | [moment@2.24.0](https://bundlephobia.com/result?p=moment@2.24.0) |  241.7 Kb |  65.9 kB | ✅    |
| New  | [moment@2.25.3](https://bundlephobia.com/result?p=moment@2.25.3) |  276.8 kB |  69.4 kB | ❌    |
|      |                                                                  | + 35.1 kB | + 3.5 kB |      |

[1]: https://dependabot.com/

**Comment by carlesnunez** [comment]
Hello @NBprojekt I think that this can be easily performed! Let me check if I can do it soon :)

I also encourage you to do it if you feel that you can do it!

**Comment by carlesnunez** [comment]
I'm working on it @NBprojekt thanks for your suggestion!

**Comment by carlesnunez** [comment]
Hello @NBprojekt! The feature requested have been released on version v1.6.0 enjoy it and provide feedback if you can.


As an example of an extreme scenario, enjoy it!

## 😱 Check my bundlephobia - New/Modified package report:

<details opened=false>
<summary>Action settings</summary>

**Treshold**: < 150000 bytes
**Strict mode**: ❌ disabled

</details>

|  | name | gzip | size | pass
| -- | ----------- | ----------------------------------------------------------------------------- | --------------------------------------------------------------------------------- | ----- |
| 🆕 | [babel-plugin-inline-import@3.0.0](https://bundlephobia.com/result?p=babel-plugin-inline-import@3.0.0)  | 2.5kB         | 6.5kB         | ✅
| ✚ | [css-loader@3.5.3](https://bundlephobia.com/result?p=css-loader@3.5.3)  | 109.0kB         | 400.5kB         | ✅
| − | [css-loader@0.28.11](https://bundlephobia.com/result?p=css-loader@0.28.11)  | 687.7kB         | 3533.6kB         |  
| | | -578.7kB         | -3133.1kB        |
| ✚ | [file-loader@6.0.0](https://bundlephobia.com/result?p=file-loader@6.0.0)  | 62.3kB         | 233.5kB         | ✅
| − | [file-loader@0.11.2](https://bundlephobia.com/result?p=file-loader@0.11.2)  | 14.8kB         | 33.8kB         |  
| | | 47.5kB         | 199.7kB        |
| ✚ | [style-loader@1.2.1](https://bundlephobia.com/result?p=style-loader@1.2.1)  | 62.7kB         | 237.9kB         | ✅
| − | [style-loader@0.23.1](https://bundlephobia.com/result?p=style-loader@0.23.1)  | 49.6kB         | 175.9kB         |  
| | | 13.1kB         | 62.0kB        |
| 🆕 | [lazysizes@5.2.0](https://bundlephobia.com/result?p=lazysizes@5.2.0)  | 3.3kB         | 7.3kB         | ✅
| 🆕 | [raw-loader@4.0.1](https://bundlephobia.com/result?p=raw-loader@4.0.1)  | 61.7kB         | 231.7kB         | ✅
| 🆕 | [react-magic-slider-dots@1.2.1](https://bundlephobia.com/result?p=react-magic-slider-dots@1.2.1)  | 1.7kB         | 4.8kB         | ✅
| ✚ | [react-slick@0.26.1](https://bundlephobia.com/result?p=react-slick@0.26.1)  | 14.5kB         | 57.1kB         | ✅
| − | [react-slick@0.24.0](https://bundlephobia.com/result?p=react-slick@0.24.0)  | 14.4kB         | 55.7kB         |  
| | | 0.1kB         | 1.4kB        |
| 🆕 | [slick-carousel@1.8.1](https://bundlephobia.com/result?p=slick-carousel@1.8.1)  | 10.3kB         | 42.3kB         | ✅
